### ISSUE TITLE
return Array{T} instead of Array{Union{T, Missing}} when applicable

### ISSUE THREAD

**Issue by mkborregaard** [evetion/GeoRasters.jl#4]
Hi, quick Q,
in DataFrames there's a lot of effort going into detecting whether you've got missing values, and if you don't, just return Array{T} rather than Array{Union{T, Missing}}. Do you have similar plans here? Or is it so rare that rasters don't have missing values that it isn't worth it?

**Comment by visr** [comment]
No I think that would probably be a nice improvement. To start with, if we have a GeoTIFF with no `NoData Value` specified in the metadata, then we can for sure just return an Array{T}.

**Comment by evetion** [comment]
I would be nice to dump the Union Missing when applicable, that would make it more usable. I have to check how to implement it though.
